BENCHMARK_LOG_PATH: test_congested_linear.txt
DEMAND_GROUND_TRUTH_PATH: demand_gt.csv
DEMAND_GROUND_TRUTH_SAVE_PATH: demand_gt.pkl
DESTINATION_N: 15
DETECTOR_LINK_MAPPING_PATH: detectors.add.50%.xml
DETECTOR_LINK_MAPPING_SAVE_PATH: detector2link.pkl
DETECTOR_RAW_DATA_PATH: detectors.xml
EDGE_DICT_PATH: edges.pkl
GRB_LICENSE_FILE: gurobi.lic
JOBS_N: 1
LINK_DENSITY_PATH: link_density.pkl
LINK_MEAN_SPEED_PATH: link_mean_speed.pkl
LINK_TRAFFIC_COUNT_PATH: link_traffic_count.pkl
LOG_STORAGE: sqlite:///db.sqlite3
LP_FILE_PATH: test_congested_linear.lp
MAX_SOLVE_TIME: 3600
NETWORK_LOADING_GAMMA_PATH: delayed_od_demand_gamma.pkl
NETWORK_LOADING_N_PATH: time_interval_needed_N.pkl
NETWORK_MEAN_SPEED_PATH: network_mean_speed.pkl
ORIGIN_N: 15
PWD: PWD
ROAD_NETWORK_PATH: osm.net.xml
ROUTE_CHOICE_PATH: route_choices.csv
ROUTE_CHOICE_SAVE_PATH: routes.pkl
ROUTE_N: 5
SAMPLER_SEED: 2025
SPACE_MEAN_EFFECTIVE_VEHICLE_LEN: 0.0055
STUDY_NAME: test_congested_linear_200_optimization
TIME_INTERVAL: 180
TIME_INTERVAL_N: 10
TRAVEL_TIME_PATH: travel_time.pkl
TRIALS_N: 200
